name: guardians_of_health 
description: "A new Flutter project." 
# The following line prevents the package from being accidentally published to 
# pub.dev using `flutter pub publish`. This is preferred for private 