// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNanffT8XL5B3ZixDPT02qdfa9x1dWzk',
    appId: '1:609237444915:web:7dc6dee4c10f6010a47646',
    messagingSenderId: '609237444915',
    projectId: 'guardians-of-health1',
    authDomain: 'guardians-of-health1.firebaseapp.com',
    storageBucket: 'guardians-of-health1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3I2dTAUyGBEl629FqnggSi9T0wrS8DI',
    appId: '1:609237444915:android:0a7743e09f0fb212a47646',
    messagingSenderId: '609237444915',
    projectId: 'guardians-of-health1',
    storageBucket: 'guardians-of-health1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXObIhRj3Y9Kcx23tMD52PwkUY6-hh27Y',
    appId: '1:609237444915:ios:a4188345454e62caa47646',
    messagingSenderId: '609237444915',
    projectId: 'guardians-of-health1',
    storageBucket: 'guardians-of-health1.firebasestorage.app',
    iosBundleId: 'com.example.guardiansOfHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXObIhRj3Y9Kcx23tMD52PwkUY6-hh27Y',
    appId: '1:609237444915:ios:a4188345454e62caa47646',
    messagingSenderId: '609237444915',
    projectId: 'guardians-of-health1',
    storageBucket: 'guardians-of-health1.firebasestorage.app',
    iosBundleId: 'com.example.guardiansOfHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsNanffT8XL5B3ZixDPT02qdfa9x1dWzk',
    appId: '1:609237444915:web:ebc0bc9bdc398e06a47646',
    messagingSenderId: '609237444915',
    projectId: 'guardians-of-health1',
    authDomain: 'guardians-of-health1.firebaseapp.com',
    storageBucket: 'guardians-of-health1.firebasestorage.app',
  );
}
